### ISSUE TITLE
Precompiled views

### ISSUE THREAD

**Issue by riezebosch** [joeaudette/cloudscribe.SimpleContent#148]
Instead of embedding all cshtml as resources you probably could include them as [precompiled views](https://scottsauber.com/2017/03/10/pre-compiling-razor-views-in-asp-net-core-with-csprojs/).

This is merely a tip than an issue.

**Comment by joeaudette** [comment]
my intention is for people to be able to override the views to customize them. with the embedded views if the user copies any view locally it will automatically use the local one instead of the embedded one. I'm not sure if that would still work if they were pre-compiled or not.
