### ISSUE TITLE
Breadcrumbs don't work when blog isn't located at /blog

### ISSUE THREAD

**Issue by godefroi** [joeaudette/cloudscribe.SimpleContent#173]
I have a starter kit set up (SimpleContent+SimpleAuth+NoDb), and I've modified the default route to make the default controller Blog:
```
    routes.MapRoute("default", "{controller=Blog}/{action=Index}/{id?}");
```
When I do this, however, the breadcrumbs don't show up. If I click "blog" in the navigation menu, I end up with an identical page, except the breadcrumbs show.

**Comment by joeaudette** [comment]
So you are not using pages for the default, you only use the blog feature?

I would say in the [projectsettings](https://github.com/joeaudette/cloudscribe.StarterKits/blob/master/SimpleContent-SimpleAuth-nodb/src/WebApp/simplecontent-settings.json) set AddBlogToPagesTree to false and add the blog to the menu from navigation.xml instead as the root/home node, and remove the attribute for treeBuilderName which is trying to build a tree for pages at the home position.

**Comment by godefroi** [comment]
I followed your suggestion, and the breadcrumbs ceased working altogether.

**Comment by joeaudette** [comment]
you might need to implement and inject your own IFindCurrentNode, you can see our default one for SimpleContent [here](https://github.com/joeaudette/cloudscribe.SimpleContent/blob/master/src/cloudscribe.SimpleContent.Web/Services/NavigationBlogNodeFinder.cs)

**Comment by joeaudette** [comment]
also make sure you didn't add the blog to the menu like this:

     <NavNode key="Blog" 
             controller="Blog" 
             action="Index" text="Blog" 
             componentVisibility="topnav" 
             >
      <Children />
    </NavNode>

if you did remove the componentVisibility attribute because in that example it is saying only show the blog in top nav, ie leave it out of any other menu views such as breacrumbs

**Comment by godefroi** [comment]
It looks like this:
```
<NavNode key="Home"
         isRootNode="false"
         parentKey="RootNode"
         controller="Blog"
         action="Index"
         text="Home"
         >
	<Children/>
</NavNode>
```

**Comment by joeaudette** [comment]
I would try it like this using a named route instead of controller/action, and make sure you use that correct route name ie whatever you use in your implementation of IBlogRoutes:

     <NavNode key="Home"
         namedRoute="blogindex"
         text="Home"
         >
	<Children/>
</NavNode>

our built in implementation of IFindCurrentNode is using the named route to determine if the current url is a blog post url. If all else fails you would have to implement and inject your own IFindCurrentNode.
I am actually working on documentation right now that explains how we implemented breadcrumbs in the blog, and it may shed some light for you.
https://www.cloudscribe.com/docs/adding-extra-breadcrumbs

**Comment by joeaudette** [comment]
note also that isRootNode and parentKey attributes are obsolete and never were actually used for anything so you can remove those from navigation.xml
