### ISSUE TITLE
Doesnt Build.... (dev or master branch)

### ISSUE THREAD

**Issue by gizmohd** [joeaudette/cloudscribe.SimpleContent#175]
Looks like the method name was changed.. but startup.cs file wasnt changed.... 

src/sourceDev.WebApp/Startup.cs
Showing the top match Last indexed a day ago
83	            services.AddScoped<cloudscribe.Web.Navigation.INavigationNodePermissionResolver, cloudscribe.SimpleContent.Web.Services.PagesNavigationNodePermissionResolver>();
84	
85	            **services.AddCloudscribeCore(Configuration);**
86	
87	            services.Configure<List<ProjectSettings>>(Configuration.GetSection("ContentProjects"));

**Comment by joeaudette** [comment]
sorry about that, a little packaging mishap, should be all better now if you open a command window on the solution folder and run the command 

    dotnet restore --no-cache

that solution is really for developing the code for SimpleContent, most people should use the [StarterKit solutions](https://github.com/joeaudette/cloudscribe.StarterKits) instead

**Comment by gizmohd** [comment]
Starter kits strengthen as well....
