### ISSUE TITLE
Comments links in blog list try to create new page

### ISSUE THREAD

**Issue by CrispinF** [joeaudette/cloudscribe.SimpleContent#21]
The comments links on blog posts in the main list view take me to creating a new page. e.g. this link https://localhost:44348/squirrel#comments 
goes to a page with 
Type your title here
meta description:
...meta...
...main content...
(this is irrespective of whether comments have already been added).
I guess this link should take the user to 
https://localhost:44348/blog/2016/03/07/squirrel#comments

**Comment by joeaudette** [comment]
fixed
