### ISSUE TITLE
Recommended Way of Adding Links to Other Pages

### ISSUE THREAD

**Issue by ezolotko** [joeaudette/cloudscribe.SimpleContent#231]
What is the best way to add links to other pages?
First comes to mind inserting relative URLs:
![image](https://user-images.githubusercontent.com/993271/35190702-0b816270-fe9a-11e7-8668-f15a42a88cb6.png)
But what if I move the site to a subdirectory later? Is there something like server-side template tag to expand page id to a full URL? Also it would be cool to have "link to page" feature in the editor that would search for an existing page (like in WordPress for example).

**Comment by joeaudette** [comment]
I generally use copy paste to add links, ie visit the page you want to link.
in the url bar control a to select the whole url, control c to copy it, then control v to paste it into the editor dialog. If users don't know this basic skill I train them to empower them.

On mac or linux control is command

For local urls I often will back space to make it a relative url after pasting.

Moving a site after it is public is a bad idea I don't have a magic solution for broken urls. [Cool urls don't change](https://www.w3.org/Provider/Style/URI)

If you do move an url you can use something like IIS Url Rewrite module to redirect to the new url.
