### ISSUE TITLE
PageTree.js currently throwing 404

### ISSUE THREAD

**Issue by scott-wi** [joeaudette/cloudscribe.SimpleContent#247]
Noticed after a nuget update that the Page Management screen was no longer working - only the "New Root Level Page" button appears and no existing pages appear.

Looking in the javascript console this message appears on loading the page:

```Loading failed for the <script> with source “http://localhost:62453/csscsr/js/pagetree.js”.```

Looks like it's related to the Web.Mvc project being merged into Web project. 

I've made the change to fix it and added a test, please let me know if it looks okay. #246

**Comment by joeaudette** [comment]
Many thanks @scott-wi ! Merged your pull request. Great work, many thanks for the fix and the unit test.
