### ISSUE TITLE
RSS not working

### ISSUE THREAD

**Issue by eBerdnA** [joeaudette/cloudscribe.SimpleContent#7]
As I was looking for a replacement for ystem.ServiceModel.Syndication to create my own rss feed I stumpled upon your [solution](https://github.com/joeaudette/cloudscribe.Syndication). According to the description a rss feed should be available at /api/rss.

So I simply cloned the most recent version of this repository and fired it up. Unfortunately no feed is available (404) at http://localhost:53941/ nor at http://localhost:53941/blog/api/rss which it should according to the information I found in `BlogMetaPartial.cshtml`.

Am I missing something or is this a bug?

**Comment by joeaudette** [comment]
thank you very much for letting me know, I had not tested rss since updating from rc2 to rtm, there were several bugs, they are fixed now. Please try the latest code and confirm that it works for you

**Comment by eBerdnA** [comment]
Thanks for your quick reponse. Feed is know generated but I found another minor issue for which I will create a pull request.
