### ISSUE TITLE
Wrong default date format with new blog post causes unhandled exception

### ISSUE THREAD

**Issue by CrispinF** [joeaudette/cloudscribe.SimpleContent#70]
NB this issue could be because some config is necessary to support en-GB, but if so I'm not sure where! Also if this is bad/missing config, it would perhaps be better to handle the exception and give the post a date/time of server-now?
Steps to reproduce:
Set site into timezone "GB".
Browser set to English UK (tested in Chrome and Edge).
Create new blog post > the default date appears in US format, e.g. 09/25/2016 12:00 AM
When save post > something went wrong on the server > this in log:
25/09/2016 17:31:40 Error 127.0.0.1 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware /Blog/AjaxPost 
An unhandled exception has occurred while executing the request&#xD;&#xA;System.FormatException: String was not recognized as a valid DateTime.&#xD;&#xA; at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)&#xD;&#xA; at cloudscribe.SimpleContent.Web.Controllers.BlogController.&lt;AjaxPost&gt;d__15.MoveNext() in D:\Development\GitHub\cloudscribe.SimpleContent\src\cloudscribe.SimpleContent.Web\Controllers\BlogController.cs:line 446
+ if I try to edit the post date to UK format, it won't let me and it reverts to US format on tabbing out of the control.

**Comment by joeaudette** [comment]
this should be fixed now. 

just learned that mentioning fix #xx in the commit message where xx is the issue number automatically closes the issue. had planned to leave it open until you confirmed the fix but I guess it makes sense that they automate that.

please do confirm that it is fixed for you

**Comment by CrispinF** [comment]
Yes fixed within the scenario. I've not tested with any altered settings, but it looks good. The date picker automatically assigns and validates a UK date. On setting a time in future, the publication time is correctly evaluated.
