### ISSUE TITLE
Prevent empty tags; duplicate tags cause error

### ISSUE THREAD

**Issue by CrispinF** [joeaudette/cloudscribe.SimpleContent#72]
Just testing tag management behaviour... a couple of simple issues:
1.
Creating or editing with ", " at the end generates a false empty category that doesn't link back to the post.
2.
setting the categories as this:
"foo,bar, ,   "
gives "something went wrong on the server" and this in the log:
Error 127.0.0.1 cloudscribe.SimpleContent.Web.Controllers.BlogController /Blog/AjaxPost 
ajax post failed with exception The instance of entity type &#x27;PostCategory&#x27; cannot be tracked because another instance of this type with the same key is already being tracked. When adding new entities, for most key types a unique temporary key value will be created if no key is set (i.e. if the key property is assigned the default value for its type). If you are explicitly setting key values for new entities, ensure they do not collide with existing entities or temporary values generated for other new entities. When attaching existing entities, ensure that only one entity instance with a given key value is attached to the context. 
This gives a similar error:
"foo,bar, Foo ,"
So does this 
"foo,bar, Foo"
( I think this just require de-duplicating the list).

**Comment by joeaudette** [comment]
thanks as always for the bug report! this is fixed now
